name: Build
on:
  push:
    branches:
      - next
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container: oven/bun:1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: bun install --frozen-lockfile --production && bun --bun run build
